# Generated by Django 5.2.12 on 2026-03-09 01:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctorschedule_timeoff_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('common_dosages', models.CharField(blank=True, help_text='e.g., 250mg, 500mg', max_length=200)),
                ('side_effects', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('diagnosis', models.TextField(help_text='Diagnosis or reason for prescription')),
                ('notes', models.TextField(blank=True, help_text='Additional instructions or notes')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('discontinued', 'Discontinued'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_until', models.DateField(blank=True, help_text='Prescription expiry date', null=True)),
                ('refills_allowed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('refills_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_emergency', models.BooleanField(default=False, help_text='Emergency prescription')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='accounts.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('pharmacy_name', models.CharField(blank=True, max_length=200)),
                ('pharmacy_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('filled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_fills', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='accounts.prescription')),
            ],
            options={
                'ordering': ['-filled_date'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(help_text='Custom medication name if not in master list', max_length=200)),
                ('dosage', models.CharField(help_text='e.g., 500mg', max_length=100)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('liquid', 'Liquid'), ('injection', 'Injection'), ('cream', 'Cream'), ('ointment', 'Ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('other', 'Other')], default='tablet', max_length=20)),
                ('frequency', models.CharField(choices=[('OD', 'Once daily'), ('BD', 'Twice daily'), ('TID', 'Three times daily'), ('QID', 'Four times daily'), ('QHS', 'At bedtime'), ('Q4H', 'Every 4 hours'), ('Q6H', 'Every 6 hours'), ('Q8H', 'Every 8 hours'), ('PRN', 'As needed'), ('STAT', 'Immediately'), ('OTHER', 'Other')], default='OD', max_length=10)),
                ('custom_frequency', models.CharField(blank=True, help_text='Custom frequency if OTHER selected', max_length=100)),
                ('duration', models.CharField(help_text='e.g., 7 days, 2 weeks, 1 month', max_length=100)),
                ('quantity', models.IntegerField(help_text='Total quantity to dispense', validators=[django.core.validators.MinValueValidator(1)])),
                ('refills', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for taking this medication')),
                ('route', models.CharField(default='Oral', help_text='e.g., Oral, Topical, Intravenous', max_length=50)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='accounts.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.prescription')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
